default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mvslim-wave-app_development

test:
  <<: *default
  database: mvslim-wave-app_test

production:
  <<: *default
  database: mvslim-wave-app_production
  username: mvslim-wave-app
  password: <%= ENV['MVSLIM-WAVE-APP_DATABASE_PASSWORD'] %>
